In [1]:
from keplergl import KeplerGl
import pandas as pd

In [2]:
df = pd.read_csv('/Users/carboni/Downloads/avant.csv')

In [3]:
df.head()

,numero_cluster,manifest_url,canvas_number,image_url,City,Country,Title,wkt,Date,Journal Type,notice
0,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://digi.ub.uni-heidelberg.de/diglit/iiif/...,359,https://digi.ub.uni-heidelberg.de/iiif/2/jbpr1...,Halle (Saale),Germany,Jahrbuch für Photographie und Reproduktionstec...,POINT(11.969722222222222 51.48277777777778),1902-01-01,Photography,NaN
1,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,109,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1908-04-01,Photography,NaN
2,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,113,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1900-02-01,Photography,NaN
3,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,130,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1902-05-01,Photography,NaN
4,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,133,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1908-04-01,Photography,NaN

In [4]:
def date_split(date:str)-> (str,str,str):
    if type(date) is not str:
        return float('nan'),float('nan'),float('nan')
    splits = date.split('-')
    vals = splits + [float('nan')] * (3 - len(splits))
    return [float(v) for v in vals]

df['year'], df['month'], df['day'] = zip(*df['Date'].apply(date_split))

df1 = df[df['year'] <= 1950.]

In [5]:
df1 = df1.drop(['month','day', 'year'], 1)

/var/folders/nw/zm4zl9xn4_d_rq3fnglst3n80000gp/T/ipykernel_9270/201933317.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df1 = df1.drop(['month','day', 'year'], 1)

In [6]:
df1['Date'] = df1['Date'].astype(str) + 'T00:00:00Z'

In [9]:
df1.head(3)

,numero_cluster,manifest_url,canvas_number,image_url,City,Country,Title,wkt,Date,Journal Type
0,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://digi.ub.uni-heidelberg.de/diglit/iiif/...,359,https://digi.ub.uni-heidelberg.de/iiif/2/jbpr1...,Halle (Saale),Germany,Jahrbuch für Photographie und Reproduktionstec...,POINT(11.969722222222222 51.48277777777778),1902-01-01T00:00:00Z,Photography
1,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,109,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1908-04-01T00:00:00Z,Photography
2,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,113,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1900-02-01T00:00:00Z,Photography

In [ ]:
df1 = df1.drop('notice', axis=1)

## Compute pivot

number of cities and number of type

In [11]:
pivot_city = pd.pivot_table(df1, values='image_url', index='City', aggfunc=pd.Series.nunique)

In [12]:
pivot_city = pivot_city.rename(columns={"image_url": "City_number"})

In [13]:
df1 = pd.merge(df1, pivot_city, on=['City'])

In [14]:
df1.head(4)

,numero_cluster,manifest_url,canvas_number,image_url,City,Country,Title,wkt,Date,Journal Type,City_number
0,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://digi.ub.uni-heidelberg.de/diglit/iiif/...,359,https://digi.ub.uni-heidelberg.de/iiif/2/jbpr1...,Halle (Saale),Germany,Jahrbuch für Photographie und Reproduktionstec...,POINT(11.969722222222222 51.48277777777778),1902-01-01T00:00:00Z,Photography,1
1,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,109,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1908-04-01T00:00:00Z,Photography,57
2,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,113,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1900-02-01T00:00:00Z,Photography,57
3,00005f00714c0e15a8d77b271a588978313509fa013f5a...,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,130,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k11...,Marseille,France,Photo-Midi,POINT(5.3763888888889 43.296666666667),1902-05-01T00:00:00Z,Photography,57

## Kepler Map

In [15]:
config = {'version': 'v1',
 'config': {'visState': {'filters': [{'dataId': ['Visual Contagions Art'],
     'id': 'gvpk0sjne',
     'name': ['Date'],
     'type': 'timeRange',
     'value': [-2461449600000, -2120631474000],
     'enlarged': True,
     'isAnimating': True,
     'plotType': 'histogram',
     'animationWindow': 'free',
     'yAxis': None,
     'speed': 1}],
   'layers': [{'id': 'gkoo0og',
     'type': 'geojson',
     'config': {'dataId': 'Visual Contagions Art',
      'label': 'Visual Contagions Art',
      'color': [248, 149, 112],
      'highlightColor': [252, 242, 26, 255],
      'columns': {'geojson': 'wkt'},
      'isVisible': True,
      'visConfig': {'opacity': 0.8,
       'strokeOpacity': 0.8,
       'thickness': 0,
       'strokeColor': None,
       'colorRange': {'name': 'Global Warming 4',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#FFC300', '#E3611C', '#831A3D', '#5A1846'],
        'reversed': True},
       'strokeColorRange': {'name': 'Global Warming',
        'type': 'sequential',
        'category': 'Uber',
        'colors': ['#5A1846',
         '#900C3F',
         '#C70039',
         '#E3611C',
         '#F1920E',
         '#FFC300']},
       'radius': 10,
       'sizeRange': [0, 10],
       'radiusRange': [20, 45],
       'heightRange': [0, 500],
       'elevationScale': 5,
       'enableElevationZoomFactor': True,
       'stroked': False,
       'filled': True,
       'enable3d': False,
       'wireframe': False},
      'hidden': False,
      'textLabel': [{'field': None,
        'color': [255, 255, 255],
        'size': 18,
        'offset': [0, 0],
        'anchor': 'start',
        'alignment': 'center'}]},
     'visualChannels': {'colorField': {'name': 'City_number',
       'type': 'integer'},
      'colorScale': 'quantile',
      'strokeColorField': None,
      'strokeColorScale': 'quantile',
      'sizeField': None,
      'sizeScale': 'linear',
      'heightField': None,
      'heightScale': 'linear',
      'radiusField': {'name': 'City_number', 'type': 'integer'},
      'radiusScale': 'sqrt'}}],
   'interactionConfig': {'tooltip': {'fieldsToShow': {'Visual Contagions Art': [{'name': 'City',
        'format': None},
       {'name': 'Title', 'format': None},
       {'name': 'image_url', 'format': None},
       {'name': 'Date', 'format': None},
       {'name': 'Country', 'format': None}]},
     'compareMode': False,
     'compareType': 'absolute',
     'enabled': True},
    'brush': {'size': 0.5, 'enabled': False},
    'geocoder': {'enabled': False},
    'coordinate': {'enabled': False}},
   'layerBlending': 'normal',
   'splitMaps': [],
   'animationConfig': {'currentTime': None, 'speed': 1}},
  'mapState': {'bearing': 0,
   'dragRotate': False,
   'latitude': 1.190983988472156,
   'longitude': -21.016067960533633,
   'pitch': 0,
   'zoom': 1.4817269048435613,
   'isSplit': False},
  'mapStyle': {'styleType': 'dark',
   'topLayerGroups': {},
   'visibleLayerGroups': {'label': True,
    'road': True,
    'border': False,
    'building': True,
    'water': True,
    'land': True,
    '3d building': False},
   'threeDBuildingColor': [9.665468314072013,
    17.18305478057247,
    31.1442867897876],
   'mapStyles': {}}}}

In [16]:
map = KeplerGl(height=600, data={'Visual Contagions Art': df1}, config=config)

User Guide: https://docs.kepler.gl/docs/keplergl-jupyter

/opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.8/site-packages/jupyter_client/session.py:718: UserWarning: Message serialization failed with:
Out of range float values are not JSON compliant
Supporting this message is deprecated in jupyter-client 7, please make sure your message is JSON-compliant
  content = self.pack(content)

In [17]:
map

KeplerGl(config={'version': 'v1', 'config': {'visState': {'filters': [{'dataId': ['Visual Contagions Art'], 'i…

In [18]:
map.save_to_html(data={'Visual Contagions Art': df1}, config=config, file_name='VC_Art.html')

Map saved to VC_Art.html!