In [1]:
import pandas as pd
import geopy.distance

In [2]:
df = pd.read_csv("/Users/carboni/Downloads/distances%2Dkm2%2Dcsv%2Ecsv.txt")

In [3]:
df.head()

,id,city,city_wd,city_x,city_y,coordinates_artlas,statefr,stateen,countryfr,countryen,...,wd_identifier,new_lat,coordinates_new,new_long,Len,instance of,country,Qid,colonne J,distance_km
0,114465,Bad Tölz,Q280491,11.556667,47.760278,"https://www.google.com/maps/place/47.760278,11...",NaN,NaN,Allemagne,Germany,...,Q280491,47.760278,https://www.google.com/maps/place/47.760277777...,11.556667,Bad Tölz,district capital,Germany,Q183,NaN,0.000035
1,106753,Altona,Q1630,10.000000,53.550000,NaN,NaN,NaN,Allemagne,Germany,...,Q1055,53.550000,NaN,10.000000,Hamburg,borough of Hamburg,Germany,Q183,NaN,0.000000
2,110543,Indre,Q457613,-1.671111,47.198611,NaN,NaN,NaN,France,France,...,Q457613,47.198611,NaN,-1.671111,Indre,commune of France,France,Q142,NaN,0.000000
3,111220,Kaliningrad,Q1829,20.500000,54.716667,NaN,NaN,NaN,Russie,Russia,...,Q1829,54.716667,NaN,20.500000,Kaliningrad,centre of oblast,Russia,Q159,NaN,0.000000
4,113068,Chersonesus,Q638445,32.625000,46.642500,"https://www.google.com/maps/place/46.6425,32.625",NaN,NaN,Ukraine,Ukraine,...,Q638445,44.612880,"https://www.google.com/maps/place/44.61288,33....",33.493873,Chersonesus,archaeological site,Ukraine,Q212,NaN,235.531789

In [27]:
df.drop(['reverse_coordinates'], axis=1, inplace=True)

In [6]:
df.dropna(subset = ["x"], inplace=True)

In [5]:
df = df.dropna(subset=['new_long','city_x'])

In [6]:
def calc_distance(x):
    site_coords = (x.city_y, x.city_x)
    place2_coords = (x.new_lat, x.new_long)
    return geopy.distance.distance(site_coords, place2_coords).km

df['distance_km2'] = df.apply(calc_distance, axis = 1)

/var/folders/nw/zm4zl9xn4_d_rq3fnglst3n80000gp/T/ipykernel_68300/2833813823.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['distance_km2'] = df.apply(calc_distance, axis = 1)

In [7]:
df

,id,city,city_wd,city_x,city_y,coordinates_artlas,statefr,stateen,countryfr,countryen,...,new_lat,coordinates_new,new_long,Len,instance of,country,Qid,colonne J,distance_km,distance_km2
0,114465,Bad Tölz,Q280491,11.556667,47.760278,"https://www.google.com/maps/place/47.760278,11...",NaN,NaN,Allemagne,Germany,...,47.760278,https://www.google.com/maps/place/47.760277777...,11.556667,Bad Tölz,district capital,Germany,Q183,NaN,0.000035,0.000035
1,106753,Altona,Q1630,10.000000,53.550000,NaN,NaN,NaN,Allemagne,Germany,...,53.550000,NaN,10.000000,Hamburg,borough of Hamburg,Germany,Q183,NaN,0.000000,0.000000
2,110543,Indre,Q457613,-1.671111,47.198611,NaN,NaN,NaN,France,France,...,47.198611,NaN,-1.671111,Indre,commune of France,France,Q142,NaN,0.000000,0.000000
3,111220,Kaliningrad,Q1829,20.500000,54.716667,NaN,NaN,NaN,Russie,Russia,...,54.716667,NaN,20.500000,Kaliningrad,centre of oblast,Russia,Q159,NaN,0.000000,0.000000
4,113068,Chersonesus,Q638445,32.625000,46.642500,"https://www.google.com/maps/place/46.6425,32.625",NaN,NaN,Ukraine,Ukraine,...,44.612880,"https://www.google.com/maps/place/44.61288,33....",33.493873,Chersonesus,archaeological site,Ukraine,Q212,NaN,235.531789,235.531789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6263,2619,Illinois,Q1204,-90.899590,41.397531,"https://www.google.com/maps/place/41.3975305,-...",NaN,NaN,États-Unis,United States,...,40.000278,https://www.google.com/maps/place/40.000277777...,-89.250278,Illinois,U.S. state,United States of America,Q30,"usa state, not cities",208.572631,208.572631
6264,2450,Seine-et-Oise,Q979470,1.154677,49.306262,"https://www.google.com/maps/place/49.306262,1....",NaN,NaN,France,France,...,48.800000,"https://www.google.com/maps/place/48.8,2.13333...",2.133333,Seine-et-Oise,department of France,France,Q142,NaN,91.031554,91.031554
6265,2436,Aveyron,Q3216,6.469784,46.167413,"https://www.google.com/maps/place/46.167413,6....",NaN,NaN,France,France,...,44.250000,"https://www.google.com/maps/place/44.25,2.7",2.700000,Aveyron,department of France,France,Q142,NaN,364.783699,364.783699
6266,44909,Fribourg,Q36378,7.150000,46.800000,NaN,NaN,NaN,Suisse,Switzerland,...,46.800000,NaN,7.150000,Fribourg,municipality of Switzerland,Switzerland,Q39,NaN,0.000000,0.000000
6267,44844,Davesco,Q5230315,8.980000,46.036667,NaN,NaN,NaN,Suisse,Switzerland,...,46.036667,NaN,8.980000,Davesco,village,Switzerland,Q39,NaN,0.000000,0.000000

In [8]:
df.to_csv('/Users/carboni/Downloads/distances_km4.csv', index=False)