# Filter dataframe by column value

filter by "Shanghai" as City

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/carboni/Downloads/cluster_160.csv")

In [7]:
df.head(3)

,numero_cluster,manifest_url,canvas_number,image_url,City,Country,Title,wkt,Date,Journal Type,notice
0,000fd000cc8ea527071a7142305b68cf69cf7436de747c...,NaN,105,https://digi.ub.uni-heidelberg.de/iiif/2/studi...,London,United Kingdom,Studio : international art,POINT(-0.1275 51.507222222222),1900-01-01,Modern Art Journal,NaN
1,000fd000cc8ea527071a7142305b68cf69cf7436de747c...,NaN,271,https://digi.ub.uni-heidelberg.de/iiif/2/revue...,Paris,France,Revue des beaux-arts de France,POINT(2.3513888888889 48.856944444444),1942-01-01,Art Journal,NaN
2,000fd000cc8ea527071a7142305b68cf69cf7436de747c...,NaN,10,https://gallica.bnf.fr/iiif/ark:/12148/bpt6k54...,Paris,France,Le Rideau artistique et littéraire,POINT(2.3513888888889 48.856944444444),1910-01-01,Theater,NaN

In [8]:
df2 = df[df['City'].notnull()]

In [12]:
df3 = df2[df2['City'].str.contains("Shanghai")]

In [13]:
df3.head()

,numero_cluster,manifest_url,canvas_number,image_url,City,Country,Title,wkt,Date,Journal Type,notice
6154,0008e9007f042bc3081c5ce78362b794809f86356c036c...,NaN,43,https://iiif.unige.ch/iiif/2/fedora_ug8056314;...,Shanghai,People's Republic of China,LINGLONG MAGAZINE,POINT(121.46666666667 31.166666666667),1935-11-06,Woman,NaN
26560,00008a00db7aafbae397c588b5b81e358799012c29a29e...,NaN,14,https://iiif.unige.ch/iiif/2/fedora_ug8049210;...,Shanghai,People's Republic of China,LINGLONG MAGAZINE,POINT(121.46666666667 31.166666666667),1934-06-27,Woman,NaN
26561,00008a00db7aafbae397c588b5b81e358799012c29a29e...,NaN,16,https://iiif.unige.ch/iiif/2/fedora_ug8101934;...,Shanghai,People's Republic of China,LINGLONG MAGAZINE,POINT(121.46666666667 31.166666666667),1933-04-12,Woman,NaN
26562,00008a00db7aafbae397c588b5b81e358799012c29a29e...,NaN,16,https://iiif.unige.ch/iiif/2/fedora_ug8102695;...,Shanghai,People's Republic of China,LINGLONG MAGAZINE,POINT(121.46666666667 31.166666666667),1933-04-26,Woman,NaN
26563,00008a00db7aafbae397c588b5b81e358799012c29a29e...,NaN,2,https://iiif.unige.ch/iiif/2/fedora_ug8051362;...,Shanghai,People's Republic of China,LINGLONG MAGAZINE,POINT(121.46666666667 31.166666666667),1932-08-03,Woman,NaN

In [14]:
df3.to_csv("Shanghai_160.csv")